"""Build the Demo section data for the project page.

Picks a few SSL-task test items (Qwen2.5-Omni base vs. Audio-R1 = exp10_t3, the pairing used in
the paper's RQ3 figure), converts their audio to MP3 under static/audio/demo/, and writes
static/js/demos.js (window.DEMOS = [...]).

Usage: python scripts/build_demos.py
"""
import json
import os
import re
import subprocess

BENCH = "/lustre09/project/6080535/jihoojo3/SSL-R1/benchmarks"
SITE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AUDIO_OUT = os.path.join(SITE, "static", "audio", "demo")
JS_OUT = os.path.join(SITE, "static", "js", "demos.js")

BASE_STEM = "qwen2.5_omni_{k}"
R1_STEM = "qwen2.5_omni_exp10_t3_{k}"

TASKS = {
    "identity": ("MMAU_temporal_ssl_identity_v2", "identity_v2_ssl_eval", "mmau_identity_v2_ssl.jsonl"),
    "inpainting": ("MMAU_temporal_ssl_inpainting", "inpainting_ssl_eval", "mmau_inpainting_ssl.jsonl"),
    "ordering": ("MMAU_temporal_ssl_3seg", "temporal_ssl_eval", "mmau_temporal_ssl_3seg.jsonl"),
}

# (task, source-id prefix). All audio in these items comes from MMAU's synthetic subset.
PICKS = [
    ("identity", "5fd6b3fc"),
    ("identity", "ff8ea71a"),
    ("inpainting", "8b4ac0fd"),
    ("ordering", "aac87e2d"),
    ("ordering", "9439b65d"),
]

IDENTITY_TEXT = {
    "only1": "Only Candidate 1 is the same recording",
    "only2": "Only Candidate 2 is the same recording",
    "both_same": "Both candidates are the same recording",
    "both_diff": "Neither candidate is the same recording",
}


def answer_letter(pred):
    m = re.findall(r"<answer>\s*\(?([A-D])", pred or "")
    return m[-1] if m else None


def think_text(pred):
    m = re.search(r"<think>(.*?)</think>", pred or "", re.S)
    return (m.group(1) if m else pred or "").strip()


def to_mp3(src, name):
    dst = os.path.join(AUDIO_OUT, name)
    subprocess.run(["ffmpeg", "-y", "-loglevel", "error", "-i", src,
                    "-ac", "1", "-ar", "16000", "-b:a", "48k", dst], check=True)
    return f"static/audio/demo/{name}"


def load_by_prefix(path, jsonl=False):
    rows = [json.loads(l) for l in open(path)] if jsonl else json.load(open(path))
    return {r["id"][:8]: r for r in rows}


def main():
    os.makedirs(AUDIO_OUT, exist_ok=True)
    demos = []
    for task, pid in PICKS:
        folder, key, qfile = TASKS[task]
        q = load_by_prefix(os.path.join(BENCH, folder, "question", qfile), jsonl=True)[pid]
        base = load_by_prefix(os.path.join(BENCH, folder, "results", BASE_STEM.format(k=key) + ".json"))[pid]
        r1 = load_by_prefix(os.path.join(BENCH, folder, "results", R1_STEM.format(k=key) + ".json"))[pid]
        adir = os.path.join(BENCH, folder, "audio")
        tag = f"{task}_{pid}"

        if task == "identity":
            inputs = [("Anchor", q["anchor_file"])] + [
                (f"Candidate {i + 1}", f) for i, f in enumerate(q["candidate_files"])]
            options = {k: IDENTITY_TEXT[v] for k, v in q["choice_states"].items()}
            question = "Which candidates are the same recording as the anchor?"
            candidates = []
        elif task == "inpainting":
            inputs = [("Masked clip", q["clip_file"])]
            candidates = [(chr(ord("A") + i), f) for i, f in enumerate(q["choice_files"])]
            options = {k: f"Candidate {k}" for k, _ in candidates}
            question = "Which candidate fills the silent gap in the clip?"
        else:
            inputs = [(f"Segment {i + 1}", f) for i, f in enumerate(q["segment_files"])]
            options = {k: v.replace(", ", " → ") for k, v in q["choice_orders"].items()}
            question = "What is the original chronological order of the shuffled segments?"
            candidates = []

        demos.append({
            "id": tag,
            "task": task,
            "question": question,
            "inputs": [{"label": lab, "src": to_mp3(os.path.join(adir, f), f"{tag}_{i}.mp3")}
                       for i, (lab, f) in enumerate(inputs)],
            "candidates": [{"label": lab, "src": to_mp3(os.path.join(adir, f), f"{tag}_cand{lab}.mp3")}
                           for lab, f in candidates],
            "options": options,
            "answer": q["answer_gt"],
            "base": {"answer": answer_letter(base["model_prediction"]),
                     "think": think_text(base["model_prediction"])},
            "r1": {"answer": answer_letter(r1["model_prediction"]),
                   "think": think_text(r1["model_prediction"])},
        })

    with open(JS_OUT, "w") as f:
        f.write("// Generated by scripts/build_demos.py -- do not edit by hand.\n")
        f.write("window.DEMOS = " + json.dumps(demos, indent=2, ensure_ascii=False) + ";\n")
    print(f"wrote {len(demos)} demos -> {JS_OUT}")


if __name__ == "__main__":
    main()
